### ISSUE TITLE
translate-maker should probably be a dependency instead of devDependency

### ISSUE THREAD

**Issue by Trakkasure** [CherryProjects/react-translate-maker#10]
In package.json, should translate-maker be a depencency instead of devDepenency? This way it is installed as part of a normal package install, and not required to be in the parent package during a production deployment.

**Comment by seeden** [comment]
@Trakkasure it is in devDependency for testing purpose only. translate-maker is in the peerDependencies because you can choose which version of translate-maker you want to use.

**Comment by Trakkasure** [comment]
Isn't react-translate-maker dependent on a specific version? I've had problems with peer dependencies, especially when trying to create npm-shrinkwrap files. Setting a depencency with version range would also achieve the result while not having to install it separately. If I want a specific version, I can install that manually and RTM will use that version instead of installing it within it's own node_modules directory.

**Comment by seeden** [comment]
It is standard as you can see for example here https://github.com/apollostack/react-apollo/blob/master/package.json#L68  React-apollo is using apollo-client as peerDependencie. That means you need to add translate-maker to your package.json (dependencies)
