### ISSUE TITLE
Nested components?

### ISSUE THREAD

**Issue by monder** [CherryProjects/react-translate-maker#4]
Hey,
I'm looking for a way to insert React components into the translated string.

Use-case:
In your example https://github.com/CherryProjects/react-translate-maker#en_usjs I want to have user names clickable.

The dirty workaround would be inserting `<a>` into the text and use `TranslateHTML`. But it doesn't work if I want links to be handled by `react-router`'s `<Link>` component.

I've tried passing the components to properties as it is in [react-intl](https://github.com/yahoo/react-intl/wiki/Components#formattedmessage) (Rich Text Formatting), but it just results in `[object Object]`
Am I missing something or this feature is not supported?

**Comment by seeden** [comment]
Hi @monder 
I added support for this. Please use the latest version of react-translate-maker (0.2.6).
Here is a small example

```js
<LocaleProvider locale="sk_SK" adapter={adapter}>
    <TranslateHTML path="test" yourParam={<a>Asdf <Translate path="inner" /></a>} />
 </LocaleProvider>
```
TranslateHTML is generating HTML output. Please be careful with unsafe characters. I will add support for this to "safe" Translate component too. But I need to do some changes in the core of  translate-maker.

**Comment by monder** [comment]
Cool. Thanks
