### ISSUE TITLE
When namespace changes, new locales for that namespace are not loaded.

### ISSUE THREAD

**Issue by Trakkasure** [CherryProjects/react-translate-maker#5]
I believe updating componentWillReceiveProps to react on namespace should help

**Comment by seeden** [comment]
I will take a look on it tomorrow. 
I am not sure if you are interested but I am using translations in my projects like css-modules. More details you can find here: https://github.com/CherryProjects/translate-maker-require-hook

**Comment by Trakkasure** [comment]
I use this in a SPA using react router. The router defines the page to show, as well as the locale file(s) to load. The files should be composed together, switching namespace makes this happen. Below is a simplified representation

<ReactRouter ...>
  <ThemingSystem ...>
    <LocaleProvider ...>
      {props.children}
    </LocaleProvider>
  </ThemingSystem>
</ReactRouter>

The above pull request will merge each namespace as it is requested into the upper level translation object. This way each component has it's own translation and the ability to use a global set of translations (like buttons, menus and other common words/phrases)

**Comment by seeden** [comment]
I merged it. I will release new version in few hours I would like to add few tests

**Comment by Trakkasure** [comment]
Were you able to get these tests added? I could pull your updates and continue writing them.

**Comment by seeden** [comment]
The new version is released with this functionality
