### ISSUE TITLE
Namespace attribute for LocaleProvider missing? 

### ISSUE THREAD

**Issue by Trakkasure** [CherryProjects/react-translate-maker#9]
This was a great feature, and my application depended on it's feature.

Will this return?

**Comment by seeden** [comment]
Hi Brandon. I will add it back.

**Comment by seeden** [comment]
@Trakkasure try to use version 0.4.4. I added test for namespace. It is the latest test. If it is not working for you please create a test case and I will update it

**Comment by Trakkasure** [comment]
Seems to be working after updating my code for promises instead of callbacks.
I also had to override resolvePath since namespace was not being passed to getFile.
I think it should, but overriding resolvePath allowed me to inject namespace. I passed an array of values to getFile by returning an array instead of a string from resolvePath.

**Comment by seeden** [comment]
@Trakkasure can you attach your implementation? I would like to see what are you doing :)
